# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.IntegerField(blank=True, null=True)),
                ('prod', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfferDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('category_secondary', models.CharField(blank=True, max_length=255, null=True)),
                ('preview_link', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('traffic_allowed', models.TextField(blank=True, null=True)),
                ('traffic_forbidden', models.TextField(blank=True, null=True)),
                ('conversion_flow', models.CharField(blank=True, max_length=511, null=True)),
                ('sign_code', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offer_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfferPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=31, null=True)),
                ('payout_value', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('revenue_value', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('cap_daily', models.IntegerField(blank=True, null=True)),
                ('remaining_cap_daily', models.IntegerField(blank=True, null=True)),
                ('cap_monthly', models.IntegerField(blank=True, null=True)),
                ('remaining_cap_monthly', models.IntegerField(blank=True, null=True)),
                ('sign_code', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offer_payout',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfferSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField(blank=True, null=True)),
                ('platforms', models.CharField(blank=True, max_length=511, null=True)),
                ('countries', models.CharField(blank=True, max_length=2045, null=True)),
                ('download_type', models.CharField(blank=True, max_length=31, null=True)),
                ('gid_idfa_needs', models.CharField(blank=True, max_length=3, null=True)),
                ('redirect_count', models.IntegerField(blank=True, null=True)),
                ('whitelist_limited', models.CharField(blank=True, max_length=3, null=True)),
                ('sign_code', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offer_setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfferSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField()),
                ('source_id', models.IntegerField()),
                ('source_offer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_link', models.CharField(blank=True, max_length=511, null=True)),
                ('sign_code', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offer_source',
                'managed': False,
            },
        ),
    ]
