# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistAffiliateOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_id', models.IntegerField(blank=True, null=True)),
                ('offer_id', models.IntegerField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blacklist_affiliate_offer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlacklistAffiliateSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_id', models.IntegerField(blank=True, null=True)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blacklist_affiliate_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlockAffiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_date', models.DateField(blank=True, null=True)),
                ('affiliate_id', models.IntegerField()),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'block_affiliate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlockSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_date', models.DateField()),
                ('source_id', models.IntegerField()),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'block_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SettingAffiliateOfferPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_id', models.IntegerField(blank=True, null=True)),
                ('offer_id', models.IntegerField(blank=True, null=True)),
                ('payout_value', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aff-Offer Payout',
                'db_table': 'setting_affiliate_offer_payout',
                'managed': False,
                'verbose_name_plural': 'Aff-Offer Payout',
            },
        ),
        migrations.CreateModel(
            name='SettingAffiliateOfferPayoutPecent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_id', models.IntegerField(blank=True, null=True)),
                ('pecent', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aff-Offer Payout Percent',
                'db_table': 'setting_affiliate_offer_payout_pecent',
                'managed': False,
                'verbose_name_plural': 'Aff-Offer Payout Percent',
            },
        ),
        migrations.CreateModel(
            name='SettingPostbackAdjustRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_sub', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliate_id', models.IntegerField(blank=True, null=True)),
                ('offer_id', models.IntegerField(blank=True, null=True)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('rate_weight', models.IntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Postback Adjust Rate',
                'db_table': 'setting_postback_adjust_rate',
                'managed': False,
                'verbose_name_plural': 'Postback Adjust Rate',
            },
        ),
        migrations.CreateModel(
            name='SettingPostbckAffiliateAdjust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_id', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('operator', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Postback Affiliate Rate',
                'db_table': 'setting_postbck_affiliate_adjust',
                'managed': False,
                'verbose_name_plural': 'Postback Affiliate Rate',
            },
        ),
        migrations.CreateModel(
            name='SettingWhitelistOfferAffiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField(blank=True, null=True)),
                ('affiliate_id', models.IntegerField(blank=True, null=True)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Whitelist Offer Affiliate',
                'db_table': 'setting_whitelist_offer_affiliate',
                'managed': False,
                'verbose_name_plural': 'Whitelist Offer Affiliate',
            },
        ),
        migrations.CreateModel(
            name='SettingWhitelistSourceAffiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('affiliate_id', models.IntegerField(blank=True, null=True)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Whitelist Source Affiliate',
                'db_table': 'setting_whitelist_source_affiliate',
                'managed': False,
                'verbose_name_plural': 'Whitelist Source Affiliate',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('addr', models.CharField(blank=True, max_length=1023, null=True)),
                ('sign_name', models.CharField(max_length=63)),
                ('enable', models.CharField(max_length=7)),
                ('whitelist_limited', models.CharField(max_length=3)),
                ('weightiness', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1023, null=True)),
                ('traffic_status', models.CharField(blank=True, max_length=7, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourceSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField()),
                ('account_cap_daily', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('conversion_cap_daily', models.IntegerField(blank=True, null=True)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'source_setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank=True, max_length=255, null=True)),
                ('passwd', models.CharField(blank=True, max_length=255, null=True)),
                ('enable', models.CharField(blank=True, max_length=7, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=31, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysAccountRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('right_id', models.IntegerField(blank=True, null=True)),
                ('available', models.CharField(blank=True, max_length=7, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_account_rights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysAccountRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('role', models.CharField(max_length=13)),
                ('aff_subs', models.CharField(blank=True, max_length=1023, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_account_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysOperatorAffiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_id', models.IntegerField(blank=True, null=True)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_operator_affiliate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysOperatorSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_operator_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(blank=True, max_length=255, null=True)),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_name', models.CharField(blank=True, max_length=255, null=True)),
                ('weightness', models.IntegerField(blank=True, null=True)),
                ('available', models.CharField(blank=True, max_length=7, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_rights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WhitelistS2S',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('ip_start', models.CharField(blank=True, max_length=15, null=True)),
                ('ip_end', models.CharField(blank=True, max_length=15, null=True)),
                ('ip_start_num', models.BigIntegerField(blank=True, null=True)),
                ('ip_end_num', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'whitelist_s2s',
                'managed': False,
            },
        ),
    ]
